"""Loading and labelling of PTB-XL metadata and waveforms.

This module owns every decision about how raw PTB-XL fields become model inputs
and targets, so that notebooks and training code cannot drift apart. In
particular it owns the mapping from SCP-ECG statements to the 5 diagnostic
superclasses, which is the label space this project uses throughout.

Key conventions, fixed here rather than at each call site:

* Labels are the 5 **diagnostic superclasses** (``NORM``, ``MI``, ``STTC``,
  ``CD``, ``HYP``), multi-label. Non-diagnostic SCP statements (form and rhythm
  statements) are ignored for labelling.
* Splits come from the published ``strat_fold`` column, used verbatim: folds
  1-8 train, 9 validation, 10 test. These are already patient-stratified.
* Records that map to **zero** superclasses are retained and flagged, never
  silently dropped (integrity rule 8). Deciding what to do with them is an
  explicit, recorded choice.
"""

from __future__ import annotations

import ast
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import numpy as np
import pandas as pd

from ecg.data.download import DatasetLayout, resolve_layout

#: The 5 PTB-XL diagnostic superclasses, in a fixed order used for every
#: label matrix, metric vector and report in this project.
SUPERCLASSES: tuple[str, ...] = ("NORM", "MI", "STTC", "CD", "HYP")

#: Published fold assignment. Folds 9 and 10 are the highest-quality folds and
#: are reserved for validation and test respectively.
TRAIN_FOLDS: tuple[int, ...] = (1, 2, 3, 4, 5, 6, 7, 8)
VAL_FOLD: int = 9
TEST_FOLD: int = 10

SamplingRate = Literal[100, 500]

#: PTB-XL anonymises ages above 89 by storing this sentinel value.
AGE_SENTINEL: int = 300

#: Metadata columns describing how an annotation was produced.
PROVENANCE_COLUMNS: tuple[str, ...] = (
    "initial_autogenerated_report",
    "validated_by_human",
    "validated_by",
    "second_opinion",
)

#: Metadata columns flagging signal-quality problems noted by the annotators.
QUALITY_COLUMNS: tuple[str, ...] = (
    "baseline_drift",
    "static_noise",
    "burst_noise",
    "electrodes_problems",
)


@dataclass(frozen=True)
class AnnotationProvenance:
    """Counts of how record annotations were produced.

    PTB-XL labels differ in evidential weight: some reports were generated by
    the recording device and never seen by a person, others were validated by a
    cardiologist, and a subset received a second opinion. Metrics computed
    against machine-only labels measure agreement with an algorithm rather than
    with clinicians, so the mix matters when interpreting results.

    Attributes:
        total: Number of records considered.
        machine_generated: Records whose report was initially autogenerated.
        human_validated: Records validated by a human annotator.
        second_opinion: Records that received a second expert opinion.
        machine_only: Autogenerated and never human-validated.
        human_only: Human-written, not autogenerated.
        n_validators: Distinct cardiologist IDs appearing in ``validated_by``.
    """

    total: int
    machine_generated: int
    human_validated: int
    second_opinion: int
    machine_only: int
    human_only: int
    n_validators: int

    def as_series(self) -> pd.Series:
        """Render the counts, with percentages, as a labelled Series.

        Returns:
            A Series suitable for direct display in a notebook.
        """
        def pct(value: int) -> str:
            return f"{value:,} ({100.0 * value / self.total:.1f}%)" if self.total else "0"

        return pd.Series(
            {
                "records": f"{self.total:,}",
                "machine-generated report": pct(self.machine_generated),
                "human-validated": pct(self.human_validated),
                "second expert opinion": pct(self.second_opinion),
                "machine-only (never human-checked)": pct(self.machine_only),
                "human-written (not autogenerated)": pct(self.human_only),
                "distinct validators": f"{self.n_validators:,}",
            }
        )


def _as_bool(series: pd.Series) -> pd.Series:
    """Coerce a PTB-XL flag column to a clean boolean Series.

    The published CSV encodes these flags inconsistently across columns and
    pandas versions -- as ``True``/``False``, ``1.0``/``0.0``, or the strings
    ``"True"``/``"False"`` -- with missing values meaning "not set".

    Args:
        series: Raw column from ``ptbxl_database.csv``.

    Returns:
        A boolean Series where missing values become ``False``.
    """
    if series.dtype == bool:
        return series
    if pd.api.types.is_numeric_dtype(series):
        return series.fillna(0).astype(float) > 0
    return (
        series.astype(str)
        .str.strip()
        .str.lower()
        .isin({"true", "1", "1.0", "yes"})
    )


def parse_scp_codes(raw: str | Mapping[str, float]) -> dict[str, float]:
    """Parse the ``scp_codes`` field into a statement -> likelihood mapping.

    The column is stored as the repr of a Python dict, e.g.
    ``"{'NORM': 100.0, 'SR': 0.0}"``. A likelihood of ``0.0`` means the
    annotator asserted the statement without quantifying confidence; it does
    **not** mean the statement is absent.

    Args:
        raw: The raw cell value, already-parsed mapping, or ``NaN``.

    Returns:
        Mapping from SCP statement code to likelihood in ``[0, 100]``.

    Raises:
        ValueError: If the cell is a string that does not parse to a dict.
    """
    if isinstance(raw, Mapping):
        return {str(k): float(v) for k, v in raw.items()}
    if not isinstance(raw, str) or not raw.strip():
        return {}
    parsed = ast.literal_eval(raw)
    if not isinstance(parsed, dict):
        raise ValueError(f"scp_codes did not parse to a dict: {raw!r}")
    return {str(k): float(v) for k, v in parsed.items()}


def load_scp_statements(layout: DatasetLayout) -> pd.DataFrame:
    """Load ``scp_statements.csv``, restricted to diagnostic statements.

    Args:
        layout: Resolved dataset paths.

    Returns:
        DataFrame indexed by SCP statement code, with a ``diagnostic_class``
        column giving the superclass, for diagnostic statements only.
    """
    statements = pd.read_csv(layout.scp_statements_csv, index_col=0)
    diagnostic = statements[statements["diagnostic"] == 1.0]
    return diagnostic


def build_superclass_map(layout: DatasetLayout) -> dict[str, str]:
    """Build the SCP-statement -> diagnostic-superclass lookup.

    Args:
        layout: Resolved dataset paths.

    Returns:
        Mapping from statement code (e.g. ``"IMI"``) to superclass
        (e.g. ``"MI"``), covering diagnostic statements only.
    """
    diagnostic = load_scp_statements(layout)
    mapping = diagnostic["diagnostic_class"].dropna().to_dict()
    return {str(code): str(cls) for code, cls in mapping.items()}


def assign_superclasses(
    scp_codes: Mapping[str, float],
    superclass_map: Mapping[str, str],
    *,
    likelihood_threshold: float = 0.0,
) -> list[str]:
    """Map one record's SCP statements to its set of diagnostic superclasses.

    Args:
        scp_codes: Parsed ``scp_codes`` for the record.
        superclass_map: Statement -> superclass lookup from
            :func:`build_superclass_map`.
        likelihood_threshold: Keep statements whose likelihood is greater than
            or equal to this value. The default of ``0.0`` keeps every asserted
            statement, because PTB-XL uses ``0.0`` to mean "asserted, confidence
            unquantified" rather than "absent". Raising this silently shrinks
            the label set, so it must be recorded in the experiment config.

    Returns:
        Superclass names in the canonical :data:`SUPERCLASSES` order, possibly
        empty.
    """
    found = {
        superclass_map[code]
        for code, likelihood in scp_codes.items()
        if code in superclass_map and likelihood >= likelihood_threshold
    }
    return [name for name in SUPERCLASSES if name in found]


def load_metadata(
    layout: DatasetLayout | Path | str,
    *,
    likelihood_threshold: float = 0.0,
) -> pd.DataFrame:
    """Load ``ptbxl_database.csv`` with parsed labels and derived columns.

    Args:
        layout: Resolved dataset paths, or a path to the dataset root.
        likelihood_threshold: Passed to :func:`assign_superclasses`.

    Returns:
        DataFrame indexed by ``ecg_id`` with the original columns plus:

        * ``scp_codes_parsed``: the parsed statement -> likelihood dict.
        * ``superclasses``: list of superclass names.
        * one boolean column per entry in :data:`SUPERCLASSES`.
        * ``n_superclasses``: label count, ``0`` for unlabelled records.
        * ``split``: ``"train"`` / ``"val"`` / ``"test"`` from ``strat_fold``.
        * ``age_censored``: ``True`` where age hit the >89 sentinel.
    """
    if not isinstance(layout, DatasetLayout):
        layout = resolve_layout(Path(layout))

    df = pd.read_csv(layout.database_csv, index_col="ecg_id")
    superclass_map = build_superclass_map(layout)

    df["scp_codes_parsed"] = df["scp_codes"].apply(parse_scp_codes)
    df["superclasses"] = df["scp_codes_parsed"].apply(
        lambda codes: assign_superclasses(
            codes, superclass_map, likelihood_threshold=likelihood_threshold
        )
    )
    for name in SUPERCLASSES:
        df[name] = df["superclasses"].apply(lambda labels, n=name: n in labels)
    df["n_superclasses"] = df["superclasses"].apply(len)
    df["split"] = df["strat_fold"].map(split_of_fold)
    df["age_censored"] = df["age"] >= AGE_SENTINEL
    return df


def split_of_fold(fold: int) -> str:
    """Map a ``strat_fold`` value to its split name.

    Args:
        fold: Published fold number, 1-10.

    Returns:
        ``"train"``, ``"val"`` or ``"test"``.

    Raises:
        ValueError: If ``fold`` is outside 1-10.
    """
    if fold in TRAIN_FOLDS:
        return "train"
    if fold == VAL_FOLD:
        return "val"
    if fold == TEST_FOLD:
        return "test"
    raise ValueError(f"Unexpected strat_fold value: {fold!r}")


def label_matrix(df: pd.DataFrame) -> np.ndarray:
    """Extract the multi-label target matrix in canonical column order.

    Args:
        df: Metadata frame from :func:`load_metadata`.

    Returns:
        Boolean array of shape ``(n_records, len(SUPERCLASSES))``.
    """
    return df[list(SUPERCLASSES)].to_numpy(dtype=bool)


def check_patient_fold_disjoint(df: pd.DataFrame) -> pd.DataFrame:
    """Find patients whose records span more than one fold.

    A non-empty result means the published folds would leak a patient between
    train and test, violating integrity rule 1. This is expected to be empty for
    PTB-XL, and asserting it makes that assumption visible rather than assumed.

    Args:
        df: Metadata frame containing ``patient_id`` and ``strat_fold``.

    Returns:
        DataFrame indexed by offending ``patient_id`` with the folds and record
        count involved. Empty when the split is clean.
    """
    grouped = df.groupby("patient_id")["strat_fold"]
    spans = grouped.nunique()
    offenders = spans[spans > 1].index
    if len(offenders) == 0:
        return pd.DataFrame(columns=["folds", "n_records"]).rename_axis("patient_id")
    return pd.DataFrame(
        {
            "folds": grouped.apply(lambda s: sorted(s.unique())).loc[offenders],
            "n_records": df.groupby("patient_id").size().loc[offenders],
        }
    )


def fold_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Build the per-fold statistics table.

    Reports size, patient count and superclass prevalence for each published
    fold, so that any drift between the training folds and the held-out folds is
    visible before test results are ever read.

    Args:
        df: Metadata frame from :func:`load_metadata`.

    Returns:
        DataFrame indexed by ``strat_fold`` with counts and per-class
        prevalences, plus an ``ALL`` row.
    """
    rows: list[pd.Series] = []
    for fold, group in df.groupby("strat_fold"):
        row = {
            "split": split_of_fold(int(fold)),
            "n_records": len(group),
            "n_patients": group["patient_id"].nunique(),
            "unlabelled": int((group["n_superclasses"] == 0).sum()),
            "mean_labels": round(float(group["n_superclasses"].mean()), 3),
        }
        for name in SUPERCLASSES:
            row[f"{name}_%"] = round(100.0 * float(group[name].mean()), 2)
        rows.append(pd.Series(row, name=int(fold)))

    table = pd.DataFrame(rows).rename_axis("strat_fold")
    overall = {
        "split": "-",
        "n_records": len(df),
        "n_patients": df["patient_id"].nunique(),
        "unlabelled": int((df["n_superclasses"] == 0).sum()),
        "mean_labels": round(float(df["n_superclasses"].mean()), 3),
    }
    for name in SUPERCLASSES:
        overall[f"{name}_%"] = round(100.0 * float(df[name].mean()), 2)
    table.loc["ALL"] = pd.Series(overall)
    return table


def cooccurrence_matrix(df: pd.DataFrame, *, normalise: bool = False) -> pd.DataFrame:
    """Compute how often superclasses appear together on the same record.

    Args:
        df: Metadata frame from :func:`load_metadata`.
        normalise: Divide each row by its diagonal, giving "given class i, the
            fraction of records that also carry class j".

    Returns:
        Square DataFrame over :data:`SUPERCLASSES`.
    """
    labels = label_matrix(df).astype(int)
    counts = labels.T @ labels
    table = pd.DataFrame(counts, index=list(SUPERCLASSES), columns=list(SUPERCLASSES))
    if normalise:
        diagonal = np.diag(counts).astype(float)
        with np.errstate(divide="ignore", invalid="ignore"):
            table = table.div(diagonal, axis=0).fillna(0.0).round(3)
    return table


def annotation_provenance(df: pd.DataFrame) -> AnnotationProvenance:
    """Summarise how the annotations in ``df`` were produced.

    Args:
        df: Metadata frame containing the :data:`PROVENANCE_COLUMNS`.

    Returns:
        The counts as an :class:`AnnotationProvenance`.

    Raises:
        KeyError: If the expected provenance columns are absent.
    """
    missing = [c for c in PROVENANCE_COLUMNS if c not in df.columns]
    if missing:
        raise KeyError(f"Missing provenance columns: {', '.join(missing)}")

    machine = _as_bool(df["initial_autogenerated_report"])
    human = _as_bool(df["validated_by_human"])
    second = _as_bool(df["second_opinion"])
    return AnnotationProvenance(
        total=len(df),
        machine_generated=int(machine.sum()),
        human_validated=int(human.sum()),
        second_opinion=int(second.sum()),
        machine_only=int((machine & ~human).sum()),
        human_only=int((~machine & human).sum()),
        n_validators=int(df["validated_by"].nunique(dropna=True)),
    )


def provenance_by_fold(df: pd.DataFrame) -> pd.DataFrame:
    """Break annotation provenance down per published fold.

    If the share of machine-only labels differs between the training folds and
    fold 10, then test metrics are partly measuring agreement with the recording
    device's algorithm rather than with cardiologists.

    Args:
        df: Metadata frame from :func:`load_metadata`.

    Returns:
        DataFrame indexed by ``strat_fold`` with percentages per provenance
        category.
    """
    rows: list[pd.Series] = []
    for fold, group in df.groupby("strat_fold"):
        stats = annotation_provenance(group)
        rows.append(
            pd.Series(
                {
                    "split": split_of_fold(int(fold)),
                    "n_records": stats.total,
                    "machine_generated_%": round(
                        100.0 * stats.machine_generated / stats.total, 2
                    ),
                    "human_validated_%": round(
                        100.0 * stats.human_validated / stats.total, 2
                    ),
                    "second_opinion_%": round(
                        100.0 * stats.second_opinion / stats.total, 2
                    ),
                    "machine_only_%": round(100.0 * stats.machine_only / stats.total, 2),
                },
                name=int(fold),
            )
        )
    return pd.DataFrame(rows).rename_axis("strat_fold")


def quality_flag_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Count records carrying each annotator-reported signal-quality flag.

    These columns are free text naming the affected leads (or ``NaN`` when
    clean), so this reports presence rather than severity. They feed the failure
    manifest required by integrity rule 8.

    Args:
        df: Metadata frame from :func:`load_metadata`.

    Returns:
        DataFrame indexed by flag name with affected record counts and
        percentages.
    """
    rows: list[pd.Series] = []
    for column in QUALITY_COLUMNS:
        if column not in df.columns:
            continue
        affected = df[column].notna() & (df[column].astype(str).str.strip() != "")
        rows.append(
            pd.Series(
                {
                    "n_records": int(affected.sum()),
                    "pct": round(100.0 * float(affected.mean()), 2),
                },
                name=column,
            )
        )
    return pd.DataFrame(rows).rename_axis("quality_flag")


#: Reasons a record is withheld from the *supervised* training set. Order is
#: fixed so manifests and reports stay comparable across runs.
SUPERVISED_EXCLUSION_REASONS: tuple[str, ...] = (
    "pacemaker",
    "electrodes_problems",
    "not_validated_by_human",
)


def supervised_exclusion_mask(df: pd.DataFrame) -> pd.DataFrame:
    """Flag, per record, each reason it is unfit for supervised training.

    Three independent concerns, deliberately kept separate rather than collapsed
    into a single boolean:

    * ``pacemaker`` -- paced rhythms have artificially regular RR intervals and
      atypical QRS morphology, making them unrepresentative input for a beat
      tokenizer.
    * ``electrodes_problems`` -- the recording itself is suspect.
    * ``not_validated_by_human`` -- the label was never checked by a
      cardiologist, so it is weak supervision.

    A record may trip more than one reason; the columns are not mutually
    exclusive.

    Args:
        df: Metadata frame from :func:`load_metadata`.

    Returns:
        Boolean DataFrame indexed like ``df``, one column per entry in
        :data:`SUPERVISED_EXCLUSION_REASONS`, plus an ``any`` column.
    """

    def flagged(column: str) -> pd.Series:
        """Treat a free-text annotation column as set when non-empty."""
        values = df[column]
        return values.notna() & (values.astype(str).str.strip() != "")

    mask = pd.DataFrame(index=df.index)
    mask["pacemaker"] = flagged("pacemaker")
    mask["electrodes_problems"] = flagged("electrodes_problems")
    mask["not_validated_by_human"] = ~_as_bool(df["validated_by_human"])
    mask["any"] = mask[list(SUPERVISED_EXCLUSION_REASONS)].any(axis=1)
    return mask


def supervised_exclusion_manifest(df: pd.DataFrame) -> pd.DataFrame:
    """Build the record-level manifest of everything the filter removes.

    Integrity rule 8 requires unusable records to be reported rather than
    silently dropped, so the excluded set is materialised as data that can be
    saved alongside a run.

    Args:
        df: Metadata frame from :func:`load_metadata`.

    Returns:
        One row per excluded record, indexed by ``ecg_id``, carrying the fold,
        the labels it would have contributed, and a ``reasons`` string listing
        every reason that applied.
    """
    mask = supervised_exclusion_mask(df)
    excluded = mask.index[mask["any"]]
    reasons = mask.loc[excluded, list(SUPERVISED_EXCLUSION_REASONS)].apply(
        lambda row: "+".join(name for name, hit in row.items() if hit), axis=1
    )
    return pd.DataFrame(
        {
            "strat_fold": df.loc[excluded, "strat_fold"],
            "split": df.loc[excluded, "split"],
            "superclasses": df.loc[excluded, "superclasses"].apply(",".join),
            "reasons": reasons,
        }
    )


def apply_supervised_filter(
    df: pd.DataFrame,
    *,
    splits: tuple[str, ...] = ("train",),
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Remove records unfit for supervised training from the chosen splits.

    By default the filter touches the training split only. Validation and test
    are left whole, so the held-out metric keeps describing the population the
    model will actually meet rather than a cleaner one.

    This filter is for the **supervised** arms only. SSL pretraining uses every
    record in the training folds, filtered or not, because it needs no labels.
    Folds 9 and 10 are excluded from pretraining entirely.

    Args:
        df: Metadata frame from :func:`load_metadata`.
        splits: Which splits to apply the filter to.

    Returns:
        Tuple of ``(kept, manifest)``: the retained records, and the manifest of
        what was removed, restricted to ``splits``.
    """
    mask = supervised_exclusion_mask(df)
    drop = mask["any"] & df["split"].isin(splits)
    manifest = supervised_exclusion_manifest(df)
    manifest = manifest[manifest["split"].isin(splits)]
    return df[~drop].copy(), manifest


def exclusion_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Tabulate how many records each exclusion reason removes, per split.

    Reasons overlap, so the per-reason columns do not sum to ``excluded_any``.

    Args:
        df: Metadata frame from :func:`load_metadata`.

    Returns:
        DataFrame indexed by split with one column per reason, the combined
        count, and the resulting retention percentage.
    """
    mask = supervised_exclusion_mask(df)
    rows: list[pd.Series] = []
    for split in ("train", "val", "test"):
        selector = df["split"] == split
        total = int(selector.sum())
        if not total:
            continue
        row = {"n_records": total}
        for reason in SUPERVISED_EXCLUSION_REASONS:
            row[reason] = int(mask.loc[selector, reason].sum())
        row["excluded_any"] = int(mask.loc[selector, "any"].sum())
        row["retained"] = total - row["excluded_any"]
        row["retained_%"] = round(100.0 * row["retained"] / total, 2)
        rows.append(pd.Series(row, name=split))
    return pd.DataFrame(rows).rename_axis("split")


def ssl_pretraining_pool(df: pd.DataFrame) -> pd.DataFrame:
    """Select the records available for self-supervised pretraining.

    Every record in the training folds is eligible, including those the
    supervised filter rejects: SSL needs no labels, so weak or absent
    annotation is no obstacle, and paced or noisy recordings are still valid
    signal to learn representations from. Folds 9 and 10 are excluded outright,
    since pretraining on held-out waveforms would leak them into the model.

    Args:
        df: Metadata frame from :func:`load_metadata`.

    Returns:
        The subset of ``df`` in the training folds.
    """
    return df[df["strat_fold"].isin(TRAIN_FOLDS)].copy()


def record_path(layout: DatasetLayout, row: pd.Series, sampling_rate: SamplingRate) -> Path:
    """Resolve the on-disk waveform path for one record.

    Args:
        layout: Resolved dataset paths.
        row: A row of the metadata frame, carrying ``filename_lr``/``filename_hr``.
        sampling_rate: 100 or 500 Hz.

    Returns:
        Path to the record stem (no extension), as ``wfdb`` expects.

    Raises:
        ValueError: If ``sampling_rate`` is not 100 or 500.
    """
    if sampling_rate == 100:
        relative = row["filename_lr"]
    elif sampling_rate == 500:
        relative = row["filename_hr"]
    else:
        raise ValueError(f"sampling_rate must be 100 or 500, got {sampling_rate!r}")
    return layout.root / str(relative)


def load_waveform(
    layout: DatasetLayout,
    row: pd.Series,
    *,
    sampling_rate: SamplingRate = 100,
) -> tuple[np.ndarray, list[str]]:
    """Read one record's 12-lead waveform.

    Args:
        layout: Resolved dataset paths.
        row: A row of the metadata frame.
        sampling_rate: 100 or 500 Hz.

    Returns:
        Tuple of the signal array with shape ``(n_samples, 12)`` in mV, and the
        lead names in file order.
    """
    import wfdb

    path = record_path(layout, row, sampling_rate)
    record = wfdb.rdrecord(str(path))
    return np.asarray(record.p_signal, dtype=np.float32), list(record.sig_name)
