"""Shared synthetic PTB-XL fixtures.

The real dataset is 3 GB and not in the repository, so every test builds against
a miniature dataset that mirrors the published column names and quirks:
stringified ``scp_codes`` dicts, mixed boolean encodings, free-text quality
flags, and the age sentinel. Nothing here touches the network or WFDB.
"""

from __future__ import annotations

# Import torch before pandas. pandas pulls in pyarrow, which on Windows loads a
# runtime DLL that makes a later "import torch" fail with WinError 1114 while
# loading c10.dll. Harmless everywhere else, including the Linux cloud runs.
import torch  # noqa: F401  # isort: skip

from pathlib import Path

import pandas as pd
import pytest

from ecg.data.ptbxl import load_metadata

#: Statement -> superclass relationships taken from the real scp_statements.csv,
#: plus the non-diagnostic rhythm statements the filters care about.
SCP_STATEMENTS = """\
,diagnostic,diagnostic_class,diagnostic_subclass
NORM,1.0,NORM,NORM
IMI,1.0,MI,IMI
ASMI,1.0,MI,AMI
NDT,1.0,STTC,STTC
LAFB,1.0,CD,LAFB/LPFB
IRBBB,1.0,CD,IRBBB
LVH,1.0,HYP,LVH
SR,0.0,,
AFIB,0.0,,
PACE,0.0,,
"""

_COLUMNS = (
    "ecg_id,patient_id,age,sex,recording_date,scp_codes,strat_fold,"
    "filename_lr,filename_hr,initial_autogenerated_report,validated_by_human,"
    "validated_by,second_opinion,baseline_drift,static_noise,burst_noise,"
    "electrodes_problems,pacemaker"
)

#: Label patterns cycled through the synthetic records, chosen so every
#: superclass appears and so multi-label records exist.
_CODE_CYCLE = (
    "{'NORM': 100.0, 'SR': 0.0}",
    "{'IMI': 80.0, 'LVH': 15.0}",
    "{'NDT': 100.0}",
    "{'LAFB': 0.0, 'ASMI': 100.0}",
    "{'IRBBB': 100.0}",
    "{'LVH': 50.0, 'NDT': 100.0}",
)


def _rows(n_records: int) -> list[str]:
    """Build synthetic metadata rows spanning all ten folds."""
    rows: list[str] = []
    for i in range(1, n_records + 1):
        fold = ((i - 1) % 10) + 1
        codes = _CODE_CYCLE[(i - 1) % len(_CODE_CYCLE)]
        # Folds 9 and 10 are fully human-validated, mirroring the real dataset;
        # the training folds are only partly validated.
        validated = "True" if fold >= 9 or i % 3 else "False"
        # A few patients contribute two recordings, to exercise de-duplication.
        patient = 100 + (i if i > 6 else (i + 1) // 2)
        rows.append(
            f"{i},{patient},{40 + (i % 50)},{i % 2},"
            f"1984-11-{(i % 28) + 1:02d} 09:{i % 60:02d}:00,\"{codes}\",{fold},"
            f"records100/00000/{i:05d}_lr,records500/00000/{i:05d}_hr,"
            f"{'True' if i % 2 else 'False'},{validated},{i % 7},"
            f"{'True' if i % 5 == 0 else 'False'},,,,,"
        )
    return rows


def database_csv(n_records: int = 60) -> str:
    """Render a synthetic ``ptbxl_database.csv``.

    Args:
        n_records: How many records to generate.

    Returns:
        CSV text.
    """
    return "\n".join([_COLUMNS, *_rows(n_records)]) + "\n"


@pytest.fixture()
def ptbxl_root(tmp_path: Path) -> Path:
    """A synthetic PTB-XL directory that passes layout validation."""
    root = tmp_path / "ptbxl"
    root.mkdir()
    (root / "ptbxl_database.csv").write_text(database_csv(), encoding="utf-8")
    (root / "scp_statements.csv").write_text(SCP_STATEMENTS, encoding="utf-8")
    (root / "records100" / "00000").mkdir(parents=True)
    (root / "records500" / "00000").mkdir(parents=True)
    return root


@pytest.fixture()
def ptbxl_metadata(ptbxl_root: Path) -> pd.DataFrame:
    """Synthetic metadata loaded through the real code path."""
    return load_metadata(ptbxl_root)
