"""Tests for PTB-XL metadata loading and superclass labelling.

Built against a synthetic mini-dataset that mirrors the published column names
and quirks (stringified ``scp_codes`` dicts, mixed boolean encodings, the age
sentinel). No real data or network access is needed, so the suite runs anywhere.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from ecg.data.ptbxl import (
    AGE_SENTINEL,
    ALL_EXCLUSION_REASONS,
    ALL_SPLIT_REASONS,
    DEFAULT_EXCLUSION_POLICY,
    LABEL_VALIDITY_REASONS,
    POPULATION_REASONS,
    SUPERCLASSES,
    SUPERVISED_EXCLUSION_REASONS,
    TEST_FOLD,
    TRAIN_FOLDS,
    VAL_FOLD,
    annotation_provenance,
    apply_supervised_filter,
    assign_superclasses,
    check_patient_fold_disjoint,
    cooccurrence_matrix,
    exclusion_summary,
    fold_summary,
    label_matrix,
    load_metadata,
    pacing_mask,
    parse_scp_codes,
    provenance_by_fold,
    quality_flag_summary,
    record_path,
    split_of_fold,
    ssl_pretraining_pool,
    supervised_exclusion_manifest,
    supervised_exclusion_mask,
)
from ecg.data.download import resolve_layout

# Statement -> superclass relationships taken from the real scp_statements.csv.
_SCP_STATEMENTS = """\
,diagnostic,diagnostic_class,diagnostic_subclass
NORM,1.0,NORM,NORM
IMI,1.0,MI,IMI
ASMI,1.0,MI,AMI
NDT,1.0,STTC,STTC
LAFB,1.0,CD,LAFB/LPFB
LVH,1.0,HYP,LVH
SR,0.0,,
AFIB,0.0,,
PACE,0.0,,
"""

# Row 5 is deliberately unlabelled (only non-diagnostic statements) to exercise
# the "retain and flag" path required by integrity rule 8. Row 3 carries an
# electrode problem; quality columns hold free text, not booleans.
#
# Splits: rows 1-2 train (fold 1), row 3 val (fold 9), rows 4-5 test (fold 10).
_DATABASE = """\
ecg_id,patient_id,age,sex,recording_date,scp_codes,strat_fold,filename_lr,filename_hr,initial_autogenerated_report,validated_by_human,validated_by,second_opinion,baseline_drift,static_noise,burst_noise,electrodes_problems,pacemaker
1,101,60,0,1984-11-09 09:17:34,"{'NORM': 100.0, 'SR': 0.0}",1,records100/00000/00001_lr,records500/00000/00001_hr,True,False,,False,,,,,
2,102,72,1,1984-11-14 12:55:37,"{'IMI': 80.0, 'LVH': 15.0}",1,records100/00000/00002_lr,records500/00000/00002_hr,False,True,3.0,True,", I-V1,",,,,
3,103,300,0,1984-11-15 10:00:00,"{'NDT': 100.0}",9,records100/00000/00003_lr,records500/00000/00003_hr,0.0,1.0,5.0,0.0,,alles,,"elektroden, V1",
4,104,45,1,1985-01-01 08:00:00,"{'LAFB': 0.0, 'ASMI': 100.0}",10,records100/00000/00004_lr,records500/00000/00004_hr,True,True,5.0,False,,,,,
5,105,55,0,1985-02-02 08:00:00,"{'AFIB': 100.0, 'SR': 0.0}",10,records100/00000/00005_lr,records500/00000/00005_hr,True,False,,False,,,,,
"""


#: Every rule, training split only -- the pre-policy default, kept for the
#: tests that exercise "held-out splits are untouched".
TRAIN_ONLY: dict[str, tuple[str, ...]] = {"train": ALL_EXCLUSION_REASONS}

#: Every rule everywhere, for the tests that check the filter can be widened.
ALL_SPLITS: dict[str, tuple[str, ...]] = {
    "train": ALL_EXCLUSION_REASONS,
    "val": ALL_EXCLUSION_REASONS,
    "test": ALL_EXCLUSION_REASONS,
}


@pytest.fixture()
def dataset_root(tmp_path: Path) -> Path:
    """Create a synthetic PTB-XL directory that passes layout validation."""
    root = tmp_path / "ptbxl"
    root.mkdir()
    (root / "ptbxl_database.csv").write_text(_DATABASE, encoding="utf-8")
    (root / "scp_statements.csv").write_text(_SCP_STATEMENTS, encoding="utf-8")
    (root / "records100" / "00000").mkdir(parents=True)
    (root / "records500" / "00000").mkdir(parents=True)
    return root


@pytest.fixture()
def metadata(dataset_root: Path) -> pd.DataFrame:
    """Load the synthetic dataset through the real code path."""
    return load_metadata(dataset_root)


class TestParseScpCodes:
    def test_parses_stringified_dict(self) -> None:
        assert parse_scp_codes("{'NORM': 100.0, 'SR': 0.0}") == {"NORM": 100.0, "SR": 0.0}

    def test_passes_through_mapping(self) -> None:
        assert parse_scp_codes({"IMI": 80}) == {"IMI": 80.0}

    def test_empty_and_missing_become_empty_dict(self) -> None:
        assert parse_scp_codes("") == {}
        assert parse_scp_codes(float("nan")) == {}

    def test_non_dict_payload_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="did not parse to a dict"):
            parse_scp_codes("['NORM']")


class TestAssignSuperclasses:
    mapping = {"NORM": "NORM", "IMI": "MI", "LVH": "HYP", "NDT": "STTC"}

    def test_returns_canonical_order(self) -> None:
        # Input order is HYP before MI; output must follow SUPERCLASSES order.
        result = assign_superclasses({"LVH": 100.0, "IMI": 100.0}, self.mapping)
        assert result == ["MI", "HYP"]

    def test_zero_likelihood_is_still_asserted(self) -> None:
        """0.0 means 'asserted, confidence unquantified', not 'absent'."""
        assert assign_superclasses({"IMI": 0.0}, self.mapping) == ["MI"]

    def test_threshold_filters_low_confidence(self) -> None:
        codes = {"IMI": 80.0, "LVH": 15.0}
        assert assign_superclasses(codes, self.mapping, likelihood_threshold=50.0) == ["MI"]

    def test_non_diagnostic_statements_ignored(self) -> None:
        assert assign_superclasses({"SR": 100.0, "AFIB": 100.0}, self.mapping) == []

    def test_duplicate_superclass_collapses(self) -> None:
        mapping = {"IMI": "MI", "ASMI": "MI"}
        assert assign_superclasses({"IMI": 100.0, "ASMI": 100.0}, mapping) == ["MI"]


class TestSplitOfFold:
    @pytest.mark.parametrize("fold", [1, 2, 3, 4, 5, 6, 7, 8])
    def test_training_folds(self, fold: int) -> None:
        assert split_of_fold(fold) == "train"

    def test_validation_and_test_folds(self) -> None:
        assert split_of_fold(9) == "val"
        assert split_of_fold(10) == "test"

    @pytest.mark.parametrize("fold", [0, 11, -1])
    def test_out_of_range_rejected(self, fold: int) -> None:
        with pytest.raises(ValueError, match="Unexpected strat_fold"):
            split_of_fold(fold)


class TestLoadMetadata:
    def test_adds_superclass_columns(self, metadata: pd.DataFrame) -> None:
        for name in SUPERCLASSES:
            assert name in metadata.columns
        assert metadata.loc[1, "superclasses"] == ["NORM"]
        assert metadata.loc[2, "superclasses"] == ["MI", "HYP"]
        assert metadata.loc[4, "superclasses"] == ["MI", "CD"]

    def test_unlabelled_records_are_retained_and_flagged(
        self, metadata: pd.DataFrame
    ) -> None:
        """Records with no diagnostic statement must survive loading."""
        assert 5 in metadata.index
        assert metadata.loc[5, "superclasses"] == []
        assert metadata.loc[5, "n_superclasses"] == 0

    def test_split_column_follows_published_folds(self, metadata: pd.DataFrame) -> None:
        assert metadata.loc[1, "split"] == "train"
        assert metadata.loc[3, "split"] == "val"
        assert metadata.loc[5, "split"] == "test"

    def test_age_sentinel_flagged(self, metadata: pd.DataFrame) -> None:
        assert metadata.loc[3, "age"] == AGE_SENTINEL
        assert bool(metadata.loc[3, "age_censored"]) is True
        assert bool(metadata.loc[1, "age_censored"]) is False

    def test_accepts_plain_path(self, dataset_root: Path) -> None:
        assert len(load_metadata(str(dataset_root))) == 5

    def test_threshold_is_applied(self, dataset_root: Path) -> None:
        strict = load_metadata(dataset_root, likelihood_threshold=50.0)
        # LVH at likelihood 15.0 drops out; IMI at 80.0 survives.
        assert strict.loc[2, "superclasses"] == ["MI"]

    def test_label_matrix_shape_and_order(self, metadata: pd.DataFrame) -> None:
        matrix = label_matrix(metadata)
        assert matrix.shape == (5, len(SUPERCLASSES))
        assert matrix[0].tolist() == [True, False, False, False, False]


class TestPatientLeakage:
    def test_clean_split_reports_nothing(self, metadata: pd.DataFrame) -> None:
        assert check_patient_fold_disjoint(metadata).empty

    def test_detects_patient_spanning_folds(self, metadata: pd.DataFrame) -> None:
        leaked = metadata.copy()
        leaked.loc[5, "patient_id"] = 101  # same patient as fold-1 record 1
        offenders = check_patient_fold_disjoint(leaked)
        assert list(offenders.index) == [101]
        assert offenders.loc[101, "folds"] == [1, 10]
        assert offenders.loc[101, "n_records"] == 2


class TestFoldSummary:
    def test_rows_cover_folds_plus_total(self, metadata: pd.DataFrame) -> None:
        table = fold_summary(metadata)
        assert set(table.index) == {1, 9, 10, "ALL"}
        assert table.loc["ALL", "n_records"] == 5
        assert table.loc["ALL", "n_patients"] == 5
        assert table.loc[1, "n_records"] == 2

    def test_counts_unlabelled_records(self, metadata: pd.DataFrame) -> None:
        table = fold_summary(metadata)
        assert table.loc[10, "unlabelled"] == 1
        assert table.loc["ALL", "unlabelled"] == 1

    def test_prevalence_columns_present(self, metadata: pd.DataFrame) -> None:
        table = fold_summary(metadata)
        for name in SUPERCLASSES:
            assert f"{name}_%" in table.columns
        assert table.loc[1, "NORM_%"] == 50.0


class TestCooccurrence:
    def test_diagonal_is_class_count(self, metadata: pd.DataFrame) -> None:
        table = cooccurrence_matrix(metadata)
        assert table.loc["MI", "MI"] == 2
        assert table.loc["NORM", "NORM"] == 1

    def test_off_diagonal_counts_pairs(self, metadata: pd.DataFrame) -> None:
        table = cooccurrence_matrix(metadata)
        assert table.loc["MI", "HYP"] == 1
        assert table.loc["HYP", "MI"] == 1
        assert table.loc["NORM", "MI"] == 0

    def test_normalised_rows_are_conditional(self, metadata: pd.DataFrame) -> None:
        table = cooccurrence_matrix(metadata, normalise=True)
        assert table.loc["MI", "MI"] == 1.0
        assert table.loc["MI", "HYP"] == 0.5  # 1 of the 2 MI records also has HYP


class TestAnnotationProvenance:
    def test_handles_mixed_boolean_encodings(self, metadata: pd.DataFrame) -> None:
        """Row 3 encodes its flags as 0.0/1.0 rather than False/True."""
        stats = annotation_provenance(metadata)
        assert stats.total == 5
        assert stats.machine_generated == 3  # rows 1, 4, 5
        assert stats.human_validated == 3  # rows 2, 3, 4
        assert stats.second_opinion == 1  # row 2

    def test_machine_only_and_human_only(self, metadata: pd.DataFrame) -> None:
        stats = annotation_provenance(metadata)
        assert stats.machine_only == 2  # rows 1 and 5: autogenerated, never checked
        assert stats.human_only == 2  # rows 2 and 3: human, not autogenerated

    def test_counts_distinct_validators(self, metadata: pd.DataFrame) -> None:
        assert annotation_provenance(metadata).n_validators == 2  # 3.0 and 5.0

    def test_as_series_includes_percentages(self, metadata: pd.DataFrame) -> None:
        series = annotation_provenance(metadata).as_series()
        assert "40.0%" in series["machine-only (never human-checked)"]

    def test_missing_columns_raise(self, metadata: pd.DataFrame) -> None:
        with pytest.raises(KeyError, match="second_opinion"):
            annotation_provenance(metadata.drop(columns=["second_opinion"]))

    def test_per_fold_breakdown(self, metadata: pd.DataFrame) -> None:
        table = provenance_by_fold(metadata)
        assert set(table.index) == {1, 9, 10}
        assert table.loc[9, "human_validated_%"] == 100.0
        assert table.loc[10, "machine_only_%"] == 50.0


class TestQualityFlags:
    def test_counts_non_empty_flags(self, metadata: pd.DataFrame) -> None:
        table = quality_flag_summary(metadata)
        assert table.loc["baseline_drift", "n_records"] == 1
        assert table.loc["static_noise", "n_records"] == 1
        assert table.loc["burst_noise", "n_records"] == 0


class TestSupervisedFilter:
    """The supervised cohort filter: pacemaker, electrodes, human validation."""

    def test_flags_each_reason_independently(self, metadata: pd.DataFrame) -> None:
        mask = supervised_exclusion_mask(metadata)
        # Rows 1 and 5 were never human-validated; row 3 has electrode problems.
        assert bool(mask.loc[1, "not_validated_by_human"]) is True
        assert bool(mask.loc[2, "not_validated_by_human"]) is False
        assert bool(mask.loc[3, "electrodes_problems"]) is True
        assert bool(mask.loc[4, "any"]) is False

    def test_pacemaker_detected_from_free_text(self, metadata: pd.DataFrame) -> None:
        """The column holds free text like 'ja, pacemaker', not a boolean."""
        df = metadata.copy()
        df["pacemaker"] = df["pacemaker"].astype(object)
        df.loc[4, "pacemaker"] = "ja, pacemaker"
        mask = supervised_exclusion_mask(df)
        assert bool(mask.loc[4, "pacemaker"]) is True
        assert bool(mask.loc[4, "any"]) is True

    def test_pacemaker_detected_from_scp_statement(self, metadata: pd.DataFrame) -> None:
        """PACE in scp_codes counts even with an empty pacemaker column.

        The two fields disagree on 15 records in the real dataset, so keying off
        the metadata column alone lets paced tracings through.
        """
        df = metadata.copy()
        df.at[4, "scp_codes_parsed"] = {"ASMI": 100.0, "PACE": 0.0}
        mask = supervised_exclusion_mask(df)
        assert df["pacemaker"].isna().all()
        assert bool(mask.loc[4, "pacemaker"]) is True

    def test_pacing_likelihood_zero_still_counts(self, metadata: pd.DataFrame) -> None:
        """0.0 means 'asserted, confidence unquantified', not 'absent'."""
        df = metadata.copy()
        df.at[2, "scp_codes_parsed"] = {"IMI": 80.0, "PACE": 0.0}
        assert bool(pacing_mask(df).loc[2]) is True

    def test_pacing_mask_takes_the_union_of_both_sources(
        self, metadata: pd.DataFrame
    ) -> None:
        df = metadata.copy()
        df["pacemaker"] = df["pacemaker"].astype(object)
        df.loc[1, "pacemaker"] = "ja, pacemaker"  # column only
        df.at[2, "scp_codes_parsed"] = {"IMI": 80.0, "PACE": 0.0}  # statement only
        flags = pacing_mask(df)
        assert bool(flags.loc[1]) is True
        assert bool(flags.loc[2]) is True
        assert bool(flags.loc[4]) is False

    def test_pacing_mask_parses_raw_scp_codes_when_needed(
        self, metadata: pd.DataFrame
    ) -> None:
        """Works on a frame that has not been through load_metadata."""
        df = metadata.drop(columns=["scp_codes_parsed"])
        df.loc[4, "scp_codes"] = "{'ASMI': 100.0, 'PACE': 0.0}"
        assert bool(pacing_mask(df).loc[4]) is True

    def test_reasons_can_overlap(self, metadata: pd.DataFrame) -> None:
        df = metadata.copy()
        df["pacemaker"] = df["pacemaker"].astype(object)
        df.loc[1, "pacemaker"] = "ja, pacemaker"  # row 1 is also unvalidated
        manifest = supervised_exclusion_manifest(df)
        assert manifest.loc[1, "reasons"] == "pacemaker+not_validated_by_human"

    def test_unlabelled_records_are_excluded(self, metadata: pd.DataFrame) -> None:
        """Row 5 carries only rhythm statements, so it has no training signal."""
        mask = supervised_exclusion_mask(metadata)
        assert bool(mask.loc[5, "unlabelled"]) is True
        assert bool(mask.loc[1, "unlabelled"]) is False

    def test_norm_with_pathology_is_excluded(self, metadata: pd.DataFrame) -> None:
        """NORM plus a pathology is self-contradictory: one label must be wrong."""
        df = metadata.copy()
        df.loc[1, "MI"] = True  # row 1 is NORM; now it is NORM+MI
        mask = supervised_exclusion_mask(df)
        assert bool(mask.loc[1, "norm_with_pathology"]) is True
        assert bool(mask.loc[1, "any"]) is True

    def test_norm_alone_is_kept(self, metadata: pd.DataFrame) -> None:
        mask = supervised_exclusion_mask(metadata)
        assert bool(mask.loc[1, "norm_with_pathology"]) is False

    def test_multiple_pathologies_without_norm_are_kept(
        self, metadata: pd.DataFrame
    ) -> None:
        """Co-occurring pathologies are ordinary multi-label, not a conflict."""
        mask = supervised_exclusion_mask(metadata)
        assert metadata.loc[2, "superclasses"] == ["MI", "HYP"]
        assert bool(mask.loc[2, "norm_with_pathology"]) is False
        assert bool(mask.loc[2, "any"]) is False

    def test_every_pathology_class_triggers_the_conflict(
        self, metadata: pd.DataFrame
    ) -> None:
        for pathology in ("MI", "STTC", "CD", "HYP"):
            df = metadata.copy()
            df.loc[1, pathology] = True
            mask = supervised_exclusion_mask(df)
            assert bool(mask.loc[1, "norm_with_pathology"]) is True, pathology

    def test_filter_touches_only_requested_splits(self, metadata: pd.DataFrame) -> None:
        """Val and test must stay whole by default."""
        kept, _ = apply_supervised_filter(metadata, policy=TRAIN_ONLY)
        # Row 1 (train, unvalidated) goes; row 5 (test, unvalidated) stays.
        assert 1 not in kept.index
        assert 5 in kept.index
        assert (kept["split"] == "test").sum() == (metadata["split"] == "test").sum()

    def test_filter_can_be_applied_to_all_splits(self, metadata: pd.DataFrame) -> None:
        kept, manifest = apply_supervised_filter(
            metadata, policy=ALL_SPLITS
        )
        assert 5 not in kept.index
        assert set(manifest["split"]) <= {"train", "val", "test"}

    def test_manifest_is_restricted_to_filtered_splits(
        self, metadata: pd.DataFrame
    ) -> None:
        _, manifest = apply_supervised_filter(metadata, policy=TRAIN_ONLY)
        assert set(manifest["split"]) == {"train"}

    def test_manifest_records_labels_that_were_lost(self, metadata: pd.DataFrame) -> None:
        """Rule 8: what was dropped, and what it would have contributed."""
        _, manifest = apply_supervised_filter(metadata, policy=TRAIN_ONLY)
        assert manifest.loc[1, "superclasses"] == "NORM"
        assert manifest.loc[1, "strat_fold"] == 1

    def test_original_frame_is_not_mutated(self, metadata: pd.DataFrame) -> None:
        before = len(metadata)
        apply_supervised_filter(metadata, policy=ALL_SPLITS)
        assert len(metadata) == before

    def test_exclusion_summary_reasons_may_exceed_any(
        self, metadata: pd.DataFrame
    ) -> None:
        """Overlapping reasons must not be double-counted in 'excluded_any'."""
        df = metadata.copy()
        df["pacemaker"] = df["pacemaker"].astype(object)
        df.loc[1, "pacemaker"] = "ja, pacemaker"
        summary = exclusion_summary(df)
        train = summary.loc["train"]
        assert train["pacemaker"] + train["not_validated_by_human"] > train["excluded_any"]
        assert train["retained"] + train["excluded_any"] == train["n_records"]

    def test_exclusion_summary_retention_percentage(self, metadata: pd.DataFrame) -> None:
        summary = exclusion_summary(metadata)
        # Train holds rows 1 and 2; only row 1 is excluded.
        assert summary.loc["train", "n_records"] == 2
        assert summary.loc["train", "retained"] == 1
        assert summary.loc["train", "retained_%"] == 50.0


class TestPatientDeduplication:
    """One recording per patient: the earliest that survives the other rules."""

    @staticmethod
    def _multi_record(metadata: pd.DataFrame) -> pd.DataFrame:
        """Give patient 101 three training records with known dates."""
        df = metadata.copy()
        df["pacemaker"] = df["pacemaker"].astype(object)
        # Rows 1, 2 and 4 become one patient, all in the training split,
        # deliberately out of date order relative to ecg_id.
        df.loc[[1, 2, 4], "patient_id"] = 101
        df.loc[[1, 2, 4], "strat_fold"] = 1
        df["split"] = df["strat_fold"].map(split_of_fold)
        df.loc[1, "recording_date"] = "1990-05-05 10:00:00"
        df.loc[2, "recording_date"] = "1984-01-01 09:00:00"  # earliest
        df.loc[4, "recording_date"] = "1995-12-31 23:00:00"
        # Make all three pass the per-record rules.
        df.loc[[1, 2, 4], "validated_by_human"] = True
        return df

    def test_keeps_exactly_one_record_per_patient(self, metadata: pd.DataFrame) -> None:
        df = self._multi_record(metadata)
        kept, _ = apply_supervised_filter(df, policy=TRAIN_ONLY)
        train = kept[kept["split"] == "train"]
        assert train["patient_id"].is_unique

    def test_keeps_the_earliest_by_recording_date(self, metadata: pd.DataFrame) -> None:
        """Not the lowest ecg_id -- row 2 is earlier than row 1."""
        df = self._multi_record(metadata)
        kept, _ = apply_supervised_filter(df, policy=TRAIN_ONLY)
        assert 2 in kept.index
        assert 1 not in kept.index
        assert 4 not in kept.index

    def test_dropped_duplicates_reach_the_manifest(self, metadata: pd.DataFrame) -> None:
        df = self._multi_record(metadata)
        _, manifest = apply_supervised_filter(df, policy=TRAIN_ONLY)
        assert manifest.loc[1, "reasons"] == "duplicate_patient_record"
        assert manifest.loc[1, "patient_id"] == 101

    def test_ties_broken_by_ecg_id_deterministically(self, metadata: pd.DataFrame) -> None:
        """Identical timestamps must still give a reproducible choice."""
        df = self._multi_record(metadata)
        df.loc[[1, 2, 4], "recording_date"] = "1990-05-05 10:00:00"
        kept, _ = apply_supervised_filter(df, policy=TRAIN_ONLY)
        assert 1 in kept.index  # lowest ecg_id wins
        assert 2 not in kept.index

    def test_missing_dates_sort_last(self, metadata: pd.DataFrame) -> None:
        """A record with a usable date beats one without."""
        df = self._multi_record(metadata)
        df.loc[2, "recording_date"] = None  # the otherwise-earliest record
        kept, _ = apply_supervised_filter(df, policy=TRAIN_ONLY)
        assert 1 in kept.index
        assert 2 not in kept.index

    def test_deduplication_runs_after_the_per_record_rules(
        self, metadata: pd.DataFrame
    ) -> None:
        """The earliest record being unusable must not cost the patient entirely."""
        df = self._multi_record(metadata)
        df.loc[2, "validated_by_human"] = False  # earliest record is now unusable
        kept, manifest = apply_supervised_filter(df, policy=TRAIN_ONLY)
        train = kept[kept["split"] == "train"]
        # Patient 101 survives via row 1, the next earliest.
        assert 101 in set(train["patient_id"])
        assert 1 in kept.index
        assert manifest.loc[2, "reasons"] == "not_validated_by_human"

    def test_can_be_switched_off(self, metadata: pd.DataFrame) -> None:
        df = self._multi_record(metadata)
        kept, _ = apply_supervised_filter(
            df, policy={"train": SUPERVISED_EXCLUSION_REASONS}
        )
        assert {1, 2, 4} <= set(kept.index)

    def test_untouched_splits_keep_duplicates(self, metadata: pd.DataFrame) -> None:
        """Val and test must keep every record, duplicates included."""
        df = metadata.copy()
        df.loc[[4, 5], "patient_id"] = 104  # both are in the test split
        kept, _ = apply_supervised_filter(df, policy=TRAIN_ONLY)
        assert {4, 5} <= set(kept.index)

    def test_summary_reports_the_duplicate_column(self, metadata: pd.DataFrame) -> None:
        df = self._multi_record(metadata)
        summary = exclusion_summary(df, policy=TRAIN_ONLY)
        assert summary.loc["train", "duplicate_patient_record"] == 2
        assert summary.loc["train", "n_rules"] == len(ALL_EXCLUSION_REASONS)
        assert summary.loc["test", "n_rules"] == 0  # not named in TRAIN_ONLY


class TestDefaultPolicy:
    """The default policy treats training and held-out folds differently."""

    def test_held_out_folds_drop_unusable_labels(self, metadata: pd.DataFrame) -> None:
        """Row 5 is unlabelled and in the test split: it cannot be scored."""
        kept, _ = apply_supervised_filter(metadata)
        assert 5 not in kept.index

    def test_held_out_folds_drop_contradictions(self, metadata: pd.DataFrame) -> None:
        df = metadata.copy()
        df.loc[4, "NORM"] = True  # row 4 is test, already MI+CD
        kept, manifest = apply_supervised_filter(df)
        assert 4 not in kept.index
        assert manifest.loc[4, "reasons"] == "norm_with_pathology"

    def test_held_out_folds_keep_cohort_quality_records(
        self, metadata: pd.DataFrame
    ) -> None:
        """Electrode problems are a cohort choice, not a label defect."""
        assert metadata.loc[3, "split"] == "val"
        kept, _ = apply_supervised_filter(metadata)
        assert 3 in kept.index

    def test_held_out_folds_keep_repeat_patients(self, metadata: pd.DataFrame) -> None:
        """De-duplication must not shrink the evaluation set."""
        df = metadata.copy()
        df.loc[[4, 5], "patient_id"] = 104
        df.loc[5, "MI"] = True  # give row 5 a label so it is not dropped
        df.loc[5, "n_superclasses"] = 1
        kept, _ = apply_supervised_filter(df)
        assert {4, 5} <= set(kept.index)

    def test_paced_records_are_excluded_from_every_split(
        self, metadata: pd.DataFrame
    ) -> None:
        """Pacing defines the study population, so it applies to val and test too."""
        df = metadata.copy()
        df["pacemaker"] = df["pacemaker"].astype(object)
        df.loc[3, "pacemaker"] = "ja, pacemaker"  # val
        df.at[4, "scp_codes_parsed"] = {"ASMI": 100.0, "PACE": 0.0}  # test
        kept, manifest = apply_supervised_filter(df)
        assert 3 not in kept.index
        assert 4 not in kept.index
        assert manifest.loc[4, "reasons"] == "pacemaker"

    def test_policy_covers_every_split(self) -> None:
        assert set(DEFAULT_EXCLUSION_POLICY) == {"train", "val", "test"}
        assert DEFAULT_EXCLUSION_POLICY["train"] == ALL_EXCLUSION_REASONS
        assert DEFAULT_EXCLUSION_POLICY["val"] == ALL_SPLIT_REASONS
        assert DEFAULT_EXCLUSION_POLICY["test"] == ALL_SPLIT_REASONS

    def test_reason_groups_partition_all_reasons(self) -> None:
        """Every reason is classified exactly once, so none can be forgotten."""
        from ecg.data.ptbxl import COHORT_QUALITY_REASONS

        groups = (LABEL_VALIDITY_REASONS, POPULATION_REASONS, COHORT_QUALITY_REASONS)
        union: set[str] = set()
        for group in groups:
            assert not union & set(group), "a reason is classified twice"
            union |= set(group)
        assert union == set(ALL_EXCLUSION_REASONS)

    def test_all_split_reasons_is_the_held_out_rule_set(self) -> None:
        assert set(ALL_SPLIT_REASONS) == set(LABEL_VALIDITY_REASONS) | set(
            POPULATION_REASONS
        )

    def test_unknown_reason_is_rejected(self, metadata: pd.DataFrame) -> None:
        """A typo in a config must fail loudly, not silently skip a rule."""
        with pytest.raises(ValueError, match="Unknown exclusion reason"):
            apply_supervised_filter(metadata, policy={"train": ("no_such_rule",)})

    def test_split_absent_from_policy_is_untouched(self, metadata: pd.DataFrame) -> None:
        kept, _ = apply_supervised_filter(metadata, policy={"train": ("unlabelled",)})
        assert {3, 4, 5} <= set(kept.index)

    def test_summary_reports_rule_counts_per_split(self, metadata: pd.DataFrame) -> None:
        summary = exclusion_summary(metadata)
        assert summary.loc["train", "n_rules"] == len(ALL_EXCLUSION_REASONS)
        assert summary.loc["val", "n_rules"] == len(ALL_SPLIT_REASONS)
        # A cohort-quality rule removes nothing from a held-out split.
        assert summary.loc["val", "electrodes_problems"] == 0
        assert summary.loc["test", "duplicate_patient_record"] == 0


class TestSslPool:
    def test_uses_training_folds_only(self, metadata: pd.DataFrame) -> None:
        pool = ssl_pretraining_pool(metadata)
        assert set(pool["strat_fold"]) <= set(TRAIN_FOLDS)
        assert VAL_FOLD not in set(pool["strat_fold"])
        assert TEST_FOLD not in set(pool["strat_fold"])

    def test_keeps_records_the_supervised_filter_rejects(
        self, metadata: pd.DataFrame
    ) -> None:
        """SSL needs no labels, so unvalidated records are still usable."""
        pool = ssl_pretraining_pool(metadata)
        assert 1 in pool.index  # train fold, never human-validated

    def test_keeps_unlabelled_records(self, metadata: pd.DataFrame) -> None:
        df = metadata.copy()
        df.loc[5, "strat_fold"] = 1  # move the unlabelled record into training
        df["split"] = df["strat_fold"].map(split_of_fold)
        pool = ssl_pretraining_pool(df)
        assert 5 in pool.index


class TestRecordPath:
    def test_resolves_both_resolutions(self, dataset_root: Path, metadata: pd.DataFrame) -> None:
        layout = resolve_layout(dataset_root)
        row = metadata.loc[1]
        assert record_path(layout, row, 100).name == "00001_lr"
        assert record_path(layout, row, 500).name == "00001_hr"
        assert record_path(layout, row, 500).is_relative_to(dataset_root)

    def test_rejects_other_rates(self, dataset_root: Path, metadata: pd.DataFrame) -> None:
        layout = resolve_layout(dataset_root)
        with pytest.raises(ValueError, match="must be 100 or 500"):
            record_path(layout, metadata.loc[1], 250)  # type: ignore[arg-type]
