"""Tests for PTB-XL metadata loading and superclass labelling.

Built against a synthetic mini-dataset that mirrors the published column names
and quirks (stringified ``scp_codes`` dicts, mixed boolean encodings, the age
sentinel). No real data or network access is needed, so the suite runs anywhere.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from ecg.data.ptbxl import (
    AGE_SENTINEL,
    SUPERCLASSES,
    annotation_provenance,
    assign_superclasses,
    check_patient_fold_disjoint,
    cooccurrence_matrix,
    fold_summary,
    label_matrix,
    load_metadata,
    parse_scp_codes,
    provenance_by_fold,
    quality_flag_summary,
    record_path,
    split_of_fold,
)
from ecg.data.download import resolve_layout

# Statement -> superclass relationships taken from the real scp_statements.csv.
_SCP_STATEMENTS = """\
,diagnostic,diagnostic_class,diagnostic_subclass
NORM,1.0,NORM,NORM
IMI,1.0,MI,IMI
ASMI,1.0,MI,AMI
NDT,1.0,STTC,STTC
LAFB,1.0,CD,LAFB/LPFB
LVH,1.0,HYP,LVH
SR,0.0,,
AFIB,0.0,,
"""

# Row 5 is deliberately unlabelled (only non-diagnostic statements) to exercise
# the "retain and flag" path required by integrity rule 8.
_DATABASE = """\
ecg_id,patient_id,age,sex,scp_codes,strat_fold,filename_lr,filename_hr,initial_autogenerated_report,validated_by_human,validated_by,second_opinion,baseline_drift,static_noise,burst_noise,electrodes_problems
1,101,60,0,"{'NORM': 100.0, 'SR': 0.0}",1,records100/00000/00001_lr,records500/00000/00001_hr,True,False,,False,,,,
2,102,72,1,"{'IMI': 80.0, 'LVH': 15.0}",1,records100/00000/00002_lr,records500/00000/00002_hr,False,True,3.0,True,", I-V1,",,,
3,103,300,0,"{'NDT': 100.0}",9,records100/00000/00003_lr,records500/00000/00003_hr,0.0,1.0,5.0,0.0,,alles,,
4,104,45,1,"{'LAFB': 0.0, 'ASMI': 100.0}",10,records100/00000/00004_lr,records500/00000/00004_hr,True,True,5.0,False,,,,
5,105,55,0,"{'AFIB': 100.0, 'SR': 0.0}",10,records100/00000/00005_lr,records500/00000/00005_hr,True,False,,False,,,,
"""


@pytest.fixture()
def dataset_root(tmp_path: Path) -> Path:
    """Create a synthetic PTB-XL directory that passes layout validation."""
    root = tmp_path / "ptbxl"
    root.mkdir()
    (root / "ptbxl_database.csv").write_text(_DATABASE, encoding="utf-8")
    (root / "scp_statements.csv").write_text(_SCP_STATEMENTS, encoding="utf-8")
    (root / "records100" / "00000").mkdir(parents=True)
    (root / "records500" / "00000").mkdir(parents=True)
    return root


@pytest.fixture()
def metadata(dataset_root: Path) -> pd.DataFrame:
    """Load the synthetic dataset through the real code path."""
    return load_metadata(dataset_root)


class TestParseScpCodes:
    def test_parses_stringified_dict(self) -> None:
        assert parse_scp_codes("{'NORM': 100.0, 'SR': 0.0}") == {"NORM": 100.0, "SR": 0.0}

    def test_passes_through_mapping(self) -> None:
        assert parse_scp_codes({"IMI": 80}) == {"IMI": 80.0}

    def test_empty_and_missing_become_empty_dict(self) -> None:
        assert parse_scp_codes("") == {}
        assert parse_scp_codes(float("nan")) == {}

    def test_non_dict_payload_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="did not parse to a dict"):
            parse_scp_codes("['NORM']")


class TestAssignSuperclasses:
    mapping = {"NORM": "NORM", "IMI": "MI", "LVH": "HYP", "NDT": "STTC"}

    def test_returns_canonical_order(self) -> None:
        # Input order is HYP before MI; output must follow SUPERCLASSES order.
        result = assign_superclasses({"LVH": 100.0, "IMI": 100.0}, self.mapping)
        assert result == ["MI", "HYP"]

    def test_zero_likelihood_is_still_asserted(self) -> None:
        """0.0 means 'asserted, confidence unquantified', not 'absent'."""
        assert assign_superclasses({"IMI": 0.0}, self.mapping) == ["MI"]

    def test_threshold_filters_low_confidence(self) -> None:
        codes = {"IMI": 80.0, "LVH": 15.0}
        assert assign_superclasses(codes, self.mapping, likelihood_threshold=50.0) == ["MI"]

    def test_non_diagnostic_statements_ignored(self) -> None:
        assert assign_superclasses({"SR": 100.0, "AFIB": 100.0}, self.mapping) == []

    def test_duplicate_superclass_collapses(self) -> None:
        mapping = {"IMI": "MI", "ASMI": "MI"}
        assert assign_superclasses({"IMI": 100.0, "ASMI": 100.0}, mapping) == ["MI"]


class TestSplitOfFold:
    @pytest.mark.parametrize("fold", [1, 2, 3, 4, 5, 6, 7, 8])
    def test_training_folds(self, fold: int) -> None:
        assert split_of_fold(fold) == "train"

    def test_validation_and_test_folds(self) -> None:
        assert split_of_fold(9) == "val"
        assert split_of_fold(10) == "test"

    @pytest.mark.parametrize("fold", [0, 11, -1])
    def test_out_of_range_rejected(self, fold: int) -> None:
        with pytest.raises(ValueError, match="Unexpected strat_fold"):
            split_of_fold(fold)


class TestLoadMetadata:
    def test_adds_superclass_columns(self, metadata: pd.DataFrame) -> None:
        for name in SUPERCLASSES:
            assert name in metadata.columns
        assert metadata.loc[1, "superclasses"] == ["NORM"]
        assert metadata.loc[2, "superclasses"] == ["MI", "HYP"]
        assert metadata.loc[4, "superclasses"] == ["MI", "CD"]

    def test_unlabelled_records_are_retained_and_flagged(
        self, metadata: pd.DataFrame
    ) -> None:
        """Records with no diagnostic statement must survive loading."""
        assert 5 in metadata.index
        assert metadata.loc[5, "superclasses"] == []
        assert metadata.loc[5, "n_superclasses"] == 0

    def test_split_column_follows_published_folds(self, metadata: pd.DataFrame) -> None:
        assert metadata.loc[1, "split"] == "train"
        assert metadata.loc[3, "split"] == "val"
        assert metadata.loc[5, "split"] == "test"

    def test_age_sentinel_flagged(self, metadata: pd.DataFrame) -> None:
        assert metadata.loc[3, "age"] == AGE_SENTINEL
        assert bool(metadata.loc[3, "age_censored"]) is True
        assert bool(metadata.loc[1, "age_censored"]) is False

    def test_accepts_plain_path(self, dataset_root: Path) -> None:
        assert len(load_metadata(str(dataset_root))) == 5

    def test_threshold_is_applied(self, dataset_root: Path) -> None:
        strict = load_metadata(dataset_root, likelihood_threshold=50.0)
        # LVH at likelihood 15.0 drops out; IMI at 80.0 survives.
        assert strict.loc[2, "superclasses"] == ["MI"]

    def test_label_matrix_shape_and_order(self, metadata: pd.DataFrame) -> None:
        matrix = label_matrix(metadata)
        assert matrix.shape == (5, len(SUPERCLASSES))
        assert matrix[0].tolist() == [True, False, False, False, False]


class TestPatientLeakage:
    def test_clean_split_reports_nothing(self, metadata: pd.DataFrame) -> None:
        assert check_patient_fold_disjoint(metadata).empty

    def test_detects_patient_spanning_folds(self, metadata: pd.DataFrame) -> None:
        leaked = metadata.copy()
        leaked.loc[5, "patient_id"] = 101  # same patient as fold-1 record 1
        offenders = check_patient_fold_disjoint(leaked)
        assert list(offenders.index) == [101]
        assert offenders.loc[101, "folds"] == [1, 10]
        assert offenders.loc[101, "n_records"] == 2


class TestFoldSummary:
    def test_rows_cover_folds_plus_total(self, metadata: pd.DataFrame) -> None:
        table = fold_summary(metadata)
        assert set(table.index) == {1, 9, 10, "ALL"}
        assert table.loc["ALL", "n_records"] == 5
        assert table.loc["ALL", "n_patients"] == 5
        assert table.loc[1, "n_records"] == 2

    def test_counts_unlabelled_records(self, metadata: pd.DataFrame) -> None:
        table = fold_summary(metadata)
        assert table.loc[10, "unlabelled"] == 1
        assert table.loc["ALL", "unlabelled"] == 1

    def test_prevalence_columns_present(self, metadata: pd.DataFrame) -> None:
        table = fold_summary(metadata)
        for name in SUPERCLASSES:
            assert f"{name}_%" in table.columns
        assert table.loc[1, "NORM_%"] == 50.0


class TestCooccurrence:
    def test_diagonal_is_class_count(self, metadata: pd.DataFrame) -> None:
        table = cooccurrence_matrix(metadata)
        assert table.loc["MI", "MI"] == 2
        assert table.loc["NORM", "NORM"] == 1

    def test_off_diagonal_counts_pairs(self, metadata: pd.DataFrame) -> None:
        table = cooccurrence_matrix(metadata)
        assert table.loc["MI", "HYP"] == 1
        assert table.loc["HYP", "MI"] == 1
        assert table.loc["NORM", "MI"] == 0

    def test_normalised_rows_are_conditional(self, metadata: pd.DataFrame) -> None:
        table = cooccurrence_matrix(metadata, normalise=True)
        assert table.loc["MI", "MI"] == 1.0
        assert table.loc["MI", "HYP"] == 0.5  # 1 of the 2 MI records also has HYP


class TestAnnotationProvenance:
    def test_handles_mixed_boolean_encodings(self, metadata: pd.DataFrame) -> None:
        """Row 3 encodes its flags as 0.0/1.0 rather than False/True."""
        stats = annotation_provenance(metadata)
        assert stats.total == 5
        assert stats.machine_generated == 3  # rows 1, 4, 5
        assert stats.human_validated == 3  # rows 2, 3, 4
        assert stats.second_opinion == 1  # row 2

    def test_machine_only_and_human_only(self, metadata: pd.DataFrame) -> None:
        stats = annotation_provenance(metadata)
        assert stats.machine_only == 2  # rows 1 and 5: autogenerated, never checked
        assert stats.human_only == 2  # rows 2 and 3: human, not autogenerated

    def test_counts_distinct_validators(self, metadata: pd.DataFrame) -> None:
        assert annotation_provenance(metadata).n_validators == 2  # 3.0 and 5.0

    def test_as_series_includes_percentages(self, metadata: pd.DataFrame) -> None:
        series = annotation_provenance(metadata).as_series()
        assert "40.0%" in series["machine-only (never human-checked)"]

    def test_missing_columns_raise(self, metadata: pd.DataFrame) -> None:
        with pytest.raises(KeyError, match="second_opinion"):
            annotation_provenance(metadata.drop(columns=["second_opinion"]))

    def test_per_fold_breakdown(self, metadata: pd.DataFrame) -> None:
        table = provenance_by_fold(metadata)
        assert set(table.index) == {1, 9, 10}
        assert table.loc[9, "human_validated_%"] == 100.0
        assert table.loc[10, "machine_only_%"] == 50.0


class TestQualityFlags:
    def test_counts_non_empty_flags(self, metadata: pd.DataFrame) -> None:
        table = quality_flag_summary(metadata)
        assert table.loc["baseline_drift", "n_records"] == 1
        assert table.loc["static_noise", "n_records"] == 1
        assert table.loc["burst_noise", "n_records"] == 0


class TestRecordPath:
    def test_resolves_both_resolutions(self, dataset_root: Path, metadata: pd.DataFrame) -> None:
        layout = resolve_layout(dataset_root)
        row = metadata.loc[1]
        assert record_path(layout, row, 100).name == "00001_lr"
        assert record_path(layout, row, 500).name == "00001_hr"
        assert record_path(layout, row, 500).is_relative_to(dataset_root)

    def test_rejects_other_rates(self, dataset_root: Path, metadata: pd.DataFrame) -> None:
        layout = resolve_layout(dataset_root)
        with pytest.raises(ValueError, match="must be 100 or 500"):
            record_path(layout, metadata.loc[1], 250)  # type: ignore[arg-type]
